apiVersion: apps/v1
kind: Deployment
metadata:
  name: retention-api-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retention-api
      track: canary
  template:
    metadata:
      labels:
        app: retention-api
        track: canary
    spec:
      containers:
        - name: api
          image: ghcr.io/mlet/retention-api:1.0.0
          ports:
            - containerPort: 8000